version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    # working_directory: ~/functions
    steps:
      - checkout
      - run: npm install
      - run: cd functions
      - run: npm install
      - run: npm run build